# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-04-25 02:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_auto_20160421_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 25, 2, 24, 41, 270174, tzinfo=utc)),
        ),
    ]
